
###
GET http://localhost:3000/tarefas

###
GET http://localhost:3000/tarefas/1
###
###
POST http://localhost:3000/tarefas
Content-Type: application/json

{
  "descricao": "Salvar pela API real usando Repository com SQL"
}

###
###
GET http://localhost:3000/tarefas
###
###
PATCH http://localhost:3000/tarefas/1
Content-Type: application/json

{
  "descricao": "Descrição atualizada direto no PostgreSQL"
}
###
GET http://localhost:3000/tarefas
###
DELETE http://localhost:3000/tarefas/11
###

GET http://localhost:3000/tarefas?busca=API

###
GET http://localhost:3000/tarefas?status=pendente
###
PATCH http://localhost:3000/tarefas/5
Content-Type: application/json

{
  "concluido": true
}